# Site
title: Semi Dev_
author: Kei Nart

# Linked
freecodecamp: https://www.freecodecamp.org/semidev_
codepen: https://codepen.io/thinhtranhnvn
github: https://github.com/thinhtranhnvn
youtube: https://www.youtube.com/channel/UC5j6yt-lodC3cTzQo1PaIAw
facebook: https://www.facebook.com/profile.php?id=61552080602484

# Preference
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
